// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mzfvlwxyqtfzzadvklbw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im16ZnZsd3h5cXRmenphZHZrbGJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0Nzg1NzAsImV4cCI6MjA2MzA1NDU3MH0.FEKi9hd_ZfB6wfI9KORd53YQipLND2FrYFB2viNru2Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);